### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by na7q** [Mason10198/SkywarnPlus#117]
**Describe the bug**
JSON errors prevents getting and clearing alerts.

**To Reproduce**
Improperly format the data.json file to reproduce. 

**Expected behavior**
Errors within the json should either delete or ignore, varying by error reason, and continue with getting alerts, or clearing.

**Files**
- SkywarnPlus Files:
  - `/tmp/SkywarnPlus/data.json`
  - SkyDescribe.py
  - SkywarnPlus.py

**Screenshots**
N/A

**Node (please complete the following information):**
 - OS: [HAMVOIP Latest]

**Additional context**
This was noticed after days of alerts that were no longer active for the counties. It was noticed by trying to run skydescribe and returned an error.

Unfortunately the json file was removed as I was testing, and didn't manage to keep the invalid formatted one. There was a line in the description that caused it to be in correctly formatted.  

Example of the format noticed in description. It was missing the outer quote.
`"description": "This alert was manually injected as a test.,`

```
[root@AllStar-Node SkywarnPlus]# python3 SkyDescribe.py 1
Traceback (most recent call last):
  File "SkyDescribe.py", line 367, in <module>
    main(sys.argv[1])
  File "SkyDescribe.py", line 271, in main
    state = load_state()
  File "SkyDescribe.py", line 98, in load_state
    state = json.load(file)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 102 column 640 (char 8748)
```

**Comment by na7q** [comment]
This bug has made the entire application useless. Literally. Every warning leads to this problem.

**Comment by mjwgeek** [comment]
I'm using the latest version and I have not encountered this "bug" that you speak of.  Perhaps it was self induced?

**Comment by na7q** [comment]
Here's an example of some of the JSON formatting problems within this. No idea of the cause as of yet. Note the "}: null," part. Where the error is, seems to vary by the alerts.

```
{
    "last_alerts": [
        [
            "High Wind Warning",
            [
                {
                    "severity": 3,
                    "description": "* WHAT...South winds 25 to 35 mph with gusts up to 60 mph expected\nat beaches and headlands. Gusts up to 45 mph for inland\ncommunities.\n\n* WHERE...Clatsop County and Tillamook County Coast, and South\nWashington Coast.\n\n* WHEN...From 7 PM this evening to 2 AM PDT Saturday.\n\n* IMPACTS...Damaging winds will blow down trees and power lines.\nWidespread power outages are expected. Travel will be difficult,\nespecially for high profile vehicles.\n\n* ADDITIONAL DETAILS...This is the first system of the season with\nwinds this strong and could cause power outages and minor damage\nalong the beaches and headlands. Similar systems later in the fall\nand winter seasons may not be as impactful.",
                    "end_time_utc": "2024-10-26T09:00:00.000000Z",
                    "county_code": "ORC007"
                },
                {
                    "severity": 3,
                    "description": "* WHAT...South winds 25 to 35 mph with gusts up to 60 mph expected\nat beaches and headlands. Gusts up to 45 mph for inland\ncommunities.\n\n* WHERE...Clatsop County and Tillamook County Coast, and South\nWashington Coast.\n\n* WHEN...From 7 PM this evening to 2 AM PDT Saturday.\n\n* IMPACTS...Damaging winds will blow down trees and power lines.\nWidespread power outages are expected. Travel will be difficult,\nespecially for high profile vehicles.\n\n* ADDITIONAL DETAILS...This is the first system of the season with\nwinds this strong and could cause power outages and minor damage\nalong the beaches and headlands. Similar systems later in the fall\nand winter seasons may not be as impactful.",
                    "end_time_utc": "2024-10-26T09:00:00.000000Z",
                    "county_code": "WAC049"
                }
            ]
        ]
    ],
    "last_sayalert": [],
    "id": null,
    "alertscript_alerts": [],
    "active_alerts": [],
    "ct": null
}: null,
    "active_alerts": []
}
```

**Comment by na7q** [comment]
Another alert with exact issue.

```
{
    "alertscript_alerts": [],
    "active_alerts": [],
    "last_sayalert": [],
    "id": null,
    "last_alerts": [
        [
            "Frost Advisory",
            [
                {
                    "county_code": "WAC059",
                    "end_time_utc": "2024-10-23T15:00:00.000000Z",
                    "severity": 1,
                    "description": "* WHAT...Temperatures as low as 35 degrees, locally as low as 32\ndegrees, will result in frost formation.\n\n* WHERE...In Oregon, North Oregon Coast Range, North Oregon Coast\nRange Lowlands, and Upper Hood River Valley. In Washington, South\nWashington Cascade Foothills.\n\n* WHEN...For the first Frost Advisory, from midnight tonight to 8 AM\nPDT Wednesday. For the second Frost Advisory, from midnight\nWednesday Night to 8 AM PDT Thursday.\n\n* IMPACTS...Frost could harm sensitive outdoor vegetation. Sensitive\noutdoor plants may be killed if left uncovered."
                },
                {
                    "county_code": "ORC007",
                    "end_time_utc": "2024-10-23T15:00:00.000000Z",
                    "severity": 1,
                    "description": "* WHAT...Temperatures as low as 35 degrees, locally as low as 32\ndegrees, will result in frost formation.\n\n* WHERE...In Oregon, North Oregon Coast Range, North Oregon Coast\nRange Lowlands, and Upper Hood River Valley. In Washington, South\nWashington Cascade Foothills.\n\n* WHEN...For the first Frost Advisory, from midnight tonight to 8 AM\nPDT Wednesday. For the second Frost Advisory, from midnight\nWednesday Night to 8 AM PDT Thursday.\n\n* IMPACTS...Frost could harm sensitive outdoor vegetation. Sensitive\noutdoor plants may be killed if left uncovered."
                }
            ]
        ]
    ],
    "ct": null
}           ]
        ]
    ]
}
```

**Comment by na7q** [comment]
> I'm using the latest version and I have not encountered this "bug" that you speak of. Perhaps it was self induced?

Self induced by the script. I will try to look over the script and see where the problem is.

**Comment by na7q** [comment]
https://github.com/na7q/SkywarnPlus/commit/97c7a7c44fde8e46294273a7d09eea166626ee61

Made some updates to it. This recognizes the improper formatting of JSON files. Resets to default. Good temp fix until I get some time to look at it more.
